kind: Service
apiVersion: v1
metadata:
  name: upload-service
spec:
  type: NodePort
  selector:
    app: MyApp
    test: test
  ports:
  - protocol: TCP
    name: test1
    port: 80
    targetPort: 9376
    nodePort: 32322
  - name: test2
    port: 8080
    targetPort: 8080

