apiVersion: v1
data:
  rules.yml: |
    groups:
    - name: pod-alert-rule
      rules:
      - alert: Deployment_Not_Running
        expr: (max(kube_deployment_status_replicas_available{}) by (deployment,namespace) == 0) * on(deployment,namespace) group_left(label_email_to)(kube_deployment_labels)
        for: 2m
        labels:
          team: node
          email_to: "{{$labels.label_email_to}}"
        annotations:
          summary: "Deployment \"{{$labels.deployment}}\" is not running"
          description: "There is no avaiable pod for the deployment {\"{$labels.deployment}}\""
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: vortex
