apiVersion: v1
kind: Service
metadata:
  name: alertmanager-external
  namespace: vortex
  labels:
    app: alertmanager
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30004
  selector:
    app: alertmanager